name: Make main.js

on:
  push:
    branches:
      - main
    paths:
      - 'js-src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "[BOT] Ensure newlines"
          file_pattern: "js-src/*.js"
        
  build_main_js:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build main.js
        run: ./tools/build.sh

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5.0.1
        with:
          commit_message: "[BOT] Build main.js"
          file_pattern: "js-min/main.js"
