name: Build main.js

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'js-src/*.js'
      - 'js-src/**/*.js'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build main.js
        run: ./tools/build.sh

      - name: Push changes
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "[build] ${{ github.event.head_commit.message }}" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

