name: Ensure Newline at End of Files

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ensure-newline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run newline script
        run: ./ensure-newline.sh

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add js-src/*
          git commit -m "Ensure newline at end of files"
          git push